using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// manages EXISTING cards (generated by CardFactory)
public class CardManager {

    private List<BaseCard> existingCards;

    public int count
    {
        get { return existingCards.Count; }
    }
    

    // Use private to hide this class from being created externally
    public CardManager()
    {
        existingCards = new List<BaseCard>();
    }

    public void registerCard(BaseCard card)
    {
        existingCards.Add(card);
    }

    public void GetNewCard(int cid) {
        existingCards.Add(card);
        
    }
}
